; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200
test_framework = unity

[env:native]
platform = native
test_ignore = embedded/*

[env:native_custom_gcc]
extends = env:native
extra_scripts = pre:modify_path.py

[env:arduino]
lib_deps = 
    https://github.com/arduino-libraries/ArduinoBLE.git
    https://github.com/arduino-libraries/Arduino_USBHostMbed5.git
    https://github.com/embeddedartistry/arduino-printf.git
    https://github.com/hideakitai/ArxTypeTraits.git
    https://github.com/KurtE/GIGA_USBHostMBed5_devices.git
    https://github.com/KurtE/MemoryHexDump.git
    https://github.com/KurtE/UNOR4-stuff.git
    https://github.com/pfeerick/elapsedMillis.git
    https://github.com/tommag/TMC5160_Arduino.git
framework = arduino
test_ignore = native/*

[env:giga_r1]
extends = env:arduino
platform = ststm32
upload_protocol = dfu

[env:giga_r1_m4]
extends = env:giga_r1
board = giga_r1_m4
build_flags = -DGIGA_R1_M4

[env:giga_r1_m4_debug]
extends = env:giga_r1_m4
build_type = debug
build_flags = 
    -DGIGA_R1_M4 
    -DDEBUG=1

[env:giga_r1_m7]
extends = env:giga_r1
board = giga_r1_m7
build_flags = -DGIGA_R1_M7

[env:giga_r1_m7_debug]
extends = env:giga_r1_m7
; build_type = debug
build_flags = 
    -DGIGA_R1_M7 
    -DDEBUG=1
