; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200
test_framework = unity

[env:native]
platform = native
test_ignore = embedded/*

[env:native_custom_gcc]
extends = env:native
extra_scripts = pre:modify_path.py

[env:arduino]
lib_deps = 
    arduino-libraries/ArduinoBLE@^1.3.6
framework = arduino
test_ignore = native/*

[env:megaatmega2560]
extends = env:arduino
platform = atmelavr
board = megaatmega2560

[env:giga_r1_dev]
extends = env:arduino
platform = https://github.com/dberlin/platform-ststm32.git#develop
platform_packages = platformio/framework-arduino-mbed@^4.1.5
;tool-dfuutil@~1.9

[env:giga_r1_m4_dev]
extends = env:giga_r1_dev
board = giga_r1_m4
build_flags = -DGIGA_R1_M4
; upload_command = arduino-cli upload --port=/dev/cu.usbmodem2101 -b arduino:mbed_giga:giga -i .pio/build/giga_r1_m4/firmware.bin

[env:giga_r1_m7_dev]
extends = env:giga_r1_dev
board = giga_r1_m7
build_flags = -DGIGA_R1_M7
; upload_command = arduino-cli upload --port=/dev/cu.usbmodem2101 -b arduino:mbed_giga:giga -i .pio/build/giga_r1_m7/firmware.bin

[env:giga_r1]
extends = env:arduino
platform = ststm32
upload_flags = 
    -v
    ; -v
    ; -v
    ; --device,0x2341:0x0366

[env:giga_r1_m4]
extends = env:giga_r1
board = giga_r1_m4
build_flags = -DGIGA_R1_M4

[env:giga_r1_m7]
extends = env:giga_r1
board = giga_r1_m7
build_flags = -DGIGA_R1_M7